# Generated by Django 5.1.4 on 2025-02-05 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresshousearticle",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accommodations.acquistionarticle",
            ),
        ),
    ]
